### ISSUE TITLE
Display current set points on `BanPick` page during second phase banpick

### ISSUE THREAD

**Issue by Nopekjk** [Duo-Cup-Korea/kdc-overlay-front#1]
Notes: the client is going to go offline while switching phase

**Comment by yhsphd** [comment]
This can be implemented without changing the backend by counting wins stored in `state.data.progress`, whose data is based on sheet

**Comment by yhsphd** [comment]
The set point visualization should be compatible both when shown and hidden because the points are 0:0 during the first phase banpick and therefore don't have to be shown. Or we can just display them on both cases.
